### ISSUE TITLE
Is this plugin maintained?

### ISSUE THREAD

**Issue by mesqueeb** [MSOpenTech/cordova-plugin-indexedDB#18]
Hi, I'd like to use this version on the latest Cordova, but I saw there's been several years since the last commit!

I also wonder if this plugin ONLY works on cordova, or will it also work in the browser?

**Comment by tripflex** [comment]
No and they can't even get their own internal PR merged that says it's not.

Here's a fork from like 2 years ago that'a  bit more recent:
https://github.com/emcniece/cordova-plugin-indexedDB2

**Comment by stammen** [comment]
This project is no longer maintained and has been archived.
