### ISSUE TITLE
Update IndexedDBShim

### ISSUE THREAD

**Issue by BigstickCarpet** [MSOpenTech/cordova-plugin-indexedDB#5]
[__TONS__ of bugs have been fixed](https://github.com/axemclion/IndexedDBShim/issues/178#issuecomment-93052746) in IndexedDBShim lately.  Please update this plugin to with the latest version of [indexeddbshim.min.js](http://nparashuram.com/IndexedDBShim/dist/indexeddbshim.min.js).

**Comment by panarasi** [comment]
Published as 0.1.2 to the plugins repo.
