### ISSUE TITLE
Requiring old syntax version of Web SQL Plugin

### ISSUE THREAD

**Issue by franciclo** [MSOpenTech/cordova-plugin-indexedDB#9]
Running Cordova Tools for Visual Studio 2015, when installing indexeddb plugin it also installs the web sql plugin (com.msopentech.websql) i think the correct plugin would be com-msopentech-websql right?

**Comment by vladimir-kotikov** [comment]
Fixed in https://github.com/MSOpenTech/cordova-plugin-indexedDB/commit/43b5fabbaf3886b01337995aa93981815929664a
